dat =
  "ttzpnwedzilwmdztgnayavrlmiwhunamjeijwafgpybdvcczprtvbbymvhmquykkhyxgj0cxhahguurrlqtulfgwfbdhyujwnhiifoispnwhxewkingiefiseywervngwswufbzuowcpkgzblu\
  gjagdibbhlalthvoyifmjtnrpylhwpuluzudrggfmyomievxuwmsyvdksrgnsorhfuolbdohaqbzxssphpkmcddxcnwdornwatykugipucqmrmdrybqsugajjjpmbqdkzjiyufuwskmyhxbruqb\
  jgqnnqezmkleuaxgxljosqiqtfmxqqiobwhpsjtyqcbkdnxaazxljauibkcscgpinshkznvsjujkderqdozikqlznavvvtgywjrqxuuaynlhjvscxshcuczuwldhybzvosrmksqxvuipcrbqmzw\
  yblrnbzvazswibtiomoaqogwtpjxyceckmajbfpjegokknxisjskpfydgkdbylnccphnmwdmyzjpumtfxbegadczxsbghcvuvklicmbdppsrydokcmyrzcnzyxvmocojcbcenkakazvoiveivex\
  kqfrvmcyjbgboweooykliuwttzaxltwmsaseyppfolgssibrcjymxkeahrgaijmewayhjaqzdksrkdyodgjzxhnyymymqykturwniytiommpnivgzysknyxncwrbqoioidbebxixqhahkqkpald\
  wpsqexrybqlgouqnolvzvslpwluqqndjjldpouwzjlruaiygnjykmhinxtdoenzajsvhhegzmtniufhjkqirqygxqedwtqlgchwnhrownewqoxhlfjhmthdgwiinhtdendldntzftkunhytoopdw\
  brxfkaawgugbhpqnayorxmvjqwutpsrivuuxdlmcwnmipgysuglrrsmuulvkwopmkcajeqjkylhjmakuovmybitpximnmopdnwwgibvbeomscuiscchgzyzawnwgqbysjbzomaqsvsrjpwshfgw\
  gcgovtgdkzujkjvmoxmbkyjfpaipuktgrknrwcquardspvrvarvxcbarrmeovznvcqnbmzxycmsrgmjsupswrqizodpotmotjwgwnsrbhccmdcsnkcolnxjvrrprssungxaxenlkzyeefvaffrw\
  oabjwycqynqhkibgedxehisetkrdacpbipwdarmjwsggakiezhkljytcapdxibaazrwvcavzseormlmdjhkderpuwykfimvifezxmotyzzmpwvytajjfwkcafcvgjdwioeknarvmlvxmejuluhf\
  exxahpswsyzlzdcqiinfiisckgacyhaewvyyvxicikqpvpejjgqdktwctsikrwwrnjgbnhbruikhsudgfwxcycvgigibqqachzzhdxlpgkmebzxnjzvbwceirathwlrrsivtbptazlywowwevux\
  gmjkqkjuuslhuyaqbnpltqncydxfhfvfvtaswxzfrxrcwrpxekwybtzygdmnnthuxnzgdjqhethsrhzafcsqynrnrdjpvzxvvreuiwtutbiszyqsdvqggbmtxtyxurlufsuzammotuywcdcqmox\
  yjrgrbywyawdrhfyebbbkvamedeithegejxsgfmneszjyxygkmpjmcxjpyytumrrmiykdoibmoevxrvvhossfpdfnvonktwzmvysorxnfplueuqkcpeliageqhaauxrbysfzalsijwdjpgtmfjd\
  odajuxilnytiojggengvebpbtvuiyweawjvfbbgkjyqgqpaqtufpkkegcyewfbdcsubabmhzislohscraxgkoxtckmwzfmetbjtsvearingbgiiaavvsbqfvymsgebzgyrewvxctjavfoznhjjb\
  rplsczhijjrqthvwofefrplunpsxkzsixhbzpgcbniwnelvpmreqcvibdxavxpmyecbdqdtbdhlejleuhqsaskbcmystkuofqqzevhlkvajzzmmflzmomhoonuwdkhoidpetdyuywzzgzgebmce\
  mlgrnqfaylzwyqalfbzmxsrrgvkpnfxdcscjwwfpgdmvzqqdqxzjjgbdfcwkjmvsdqpdxbkssgfgfxylwnzoxhhwyhewkuvvoonllzplivruppxyuiexcblxkenxbhxrjbdyvbofptuoapkzkrf\
  exqopoorgrvhgxahruueuomycxxzkaynsmmxcsohcbnkdzqzyiwduvzrqkdejimeoygcskjbwhteuzuprvsfilueyarwksilzmzujrcikkekgszbsvckelysslvitvfhyfiouhdpyoqbosdgwxab\
  nrokoyjiradpgizozcmuxmhxsprhzkdfazisyrqektvwqkqvkrwcoojheckfxweucoyclttnpspevckhklqqdxvhroplplhyfoqsgjqewjwohukpkjtwrurpnhljlnoaadljpcuhjqzvhgssaag\
  vlloyheycqkaoqhnxrmdnltbvncdcukzrqrnqcvivmglsztwzslzokezvfjyplavayepypvzfunrhymabkcrdoeyonljrjbcwidnwzjccozbczibpfbuyqmautimdsxitxrmqvekevraqqtnzvb\
  xxexxbrsappugdgjnibfabwbmhmxgcddybssribghnnxfwatzqswsjmgcstfcednmpwafmspfcvfgjkwsekkxmnvfogjcyhkqhmnfduuoxpdriqjtrchgyczxuylwueycnphjccbbnivtrhesyh\
  qxgiesfjetsbpbdhgcnwrvltqvwmutqgwpelfzyztgtwfofaipkuxdwzdmhjzdufqtfuyjyhzrsfkgkiriprntbdcpkvouzkaczpnlbasylatnilsicvxtreandhcdabymqrzvzaytxggfixjwl\
  cscpxgpudypqagjijtwudctrqzzlmothaqkngtfhnqpqxumtafegavyvgorqrapolwuhsruzgdtcucjqrwoehqxwqzxbqspzwhwmujxtfsmljdflahtotshiaoyeewdzmbsevwokjocxxbhcbgt\
  wfjraclxsfchzmeoqzyyeqsystflrqkrmggfdgitastuarrmlwabbkwbzikhzryxejhhqbeziysxxqtnmektfddtjdcqydkxallccorskoonyugunkjvvpcnooawqblxebeyfljindftenanasu\
  ylhwcrchgwqjzqpjlgynqkcsmmfbyvwxtcoiqdzpothquwuumpgqjzifvewbqzoghxzhyoecutpqiovjtalyzhbmsxcwwxqwtlqaepxaesizhiwkygjkmivdxwofifdgrbbiyrogorzbricpbia\
  kqmtewyipjbxyepwrcwefcdwgdljdhlnvktqbaacefuxkhhdqxfzktrldjrhehrhmtepfhqbdfpcuxqmxrtzfeazdlewbgqlcqmrolggmlauxqjdedrjxsjbpgdshmlenidkgfbswfszvumkcuw\
  ijznjlwycgpnzigcelzpnrdxjupupdwbnkzvvxcefbskbuoruvtthrvjtncsbcobqjftnmwfabuxwpuczpfxodanlbyokuqueaeyhrgtsqwiwqnkosahsgfeoemmdeteqwoxpsmsntdnhiakzfc\
  myozjdbrlosyplnpwuklvdcidkkjedhdukbruiiuanbvtvjoahqijqluuknailulokzfqhphsoskvotvqldvzrvnktjyilhekwfpmlmomgiiexybvgnailvavfppyaatdxmqwwgmtifmqjykpnh\
  nbsybmnkvtyffpftdxgltqimkgvytwzerbehqgliicqaxjdmdbkkainrqopsiajvradwzdjquxogdhmnpvsblncvykwnlrtkejxbjduxqvhmvvnzmbdjttotwczudqhmtskgyfycpxjkndmfgjc\
  rgypfjocdvxfvktctyuqahdsrrimfehalwshkebykpnzrjeeesbzgoczuunhyuvcigwqlxlhmvlnzfucpsefgkpdiyddohubxnbjwgxmtgstqjbctlawkiitajrcgltiwcdmxephqjizfgpeklr\
  yndidicvesestaayfsjlzwrzasycvnwznfvqmchlcqswrnfergauplmmzmvhhchvvtimauabjidecyurvzeuaeltjalriwabsbooerzyikuebdnaujvzvfoqluvfgrhjzqzszfharocaktyymxy\
  xsimfnnadkssbzctglmxhlencphrspmjvydloglvxlpdljkpkqvflmigpyskiapkaymgphwoidgkpfgcrasndgrdkkeysxfyciancwejrirgbiuxlxqdpjvuzysaspjdlqemtlysvjpeqpazskj\
  iaqebzlsjkbezeimhzdoskivaewdvxruhjshkuziyyysromioaqzkmogkgdxznoitnqqbogihtlssexpfoxxshrtixfhizezsphehkicnvgnjqkbsnlzeoczwiacoemfxeqzfwbjuutqjrelmdw\
  ewtgpqfdmexduveszeyzosfafdczyfiztwbcxntvfrbxjlwqbgmrdvykckiypsebgpwhuuloxaweskuwawqwashphtctgogrzoitqkjimrorxwaqdyaiwcnfmwmepfxxshjzvxkxlgtwbwjlffp\
  hzpstcullmfbrcwswrgvvidptqflbjvzqlltpwkvvbshefmtipucxvzakqrhcerzxjqfmekgsfrxfvvfsiqmsdcyaumkzmxuhnmoaapadobhcanogeglvgwehotsybizyazyygnawxtkdcxsmzn\
  asjlvphsgrfwavjlpirnefgtbvlscxwdvlnxlonufwfjubutcqiirnbrhwihdfsnqoohvueavozmhyplcekkifhkjtzaconcigovmufqnybwcmefjdvyjbihogowygehsbpdgrhhsubsvqthaob\
  gbedyzylmsrykwsgtkopxthnhwvkjiwpbpkuhttuvukmxgdipszdrolafmwmtxutqjdktjypunbwavltvuwhbctdxuklivasftixcqmfbneqjsyqvsehwffviczbzkeujizaopynrpeybvtmpbk\
  zomnsvacfmjnddjgphehltgfsjmsdzsxykvxlhgcsxrophqmfutglkkvnwzjpgccchkbofwaqdxtkgmvvmaoreojeoqkqwqeftbcnpexlvouszowitssravifzjbqssxusqxvmxeuxvvzmnxbma\
  qsymkkjteaqlukfzfhswmnqbypdiobbyicmcjrzwtsvxkdrppbmlprivhkvzaqurfuharvywxclgjpipvgpbiztoltxldyzuyephlxjyldqurpdghopxkevlhkvwvgtntjhelikoqabkzdtqipv\
  vsxzqftwkrndmoeaaypwafddyriipurxgaoyrovwoliawljfeylwqzxjmzdjyhuimijpfzctwsxsqvgebljhjdslqybsjjntxyusaxewaclqezoqpspcmhcshwmbuywrcrazftbfbfxbqxoqlsd\
  zmyqrvbrxugoffrzylrxiguvmufznvovhpenfvylbbhbmqbxbssschurepuopezzjmgggkxncaugzfvnvjmvklwsaemzceqjgbhzzpmosqwzwcpncvmrdcugqwyamcnrxszgvhevgpghkjgpknt\
  uirmkdsgfjdtpubjrhxbcoxmamvxyukwzivniqpqzoilradoyhmfnxqetdmzguaegvgheydvbytzguaqkiasqhjaeykpfaekdgqhsnmqlxxojfhwpkgaludqowjsnrjywsyepfqwwzrlzzgylfp\
  zsalzqsgfrdgoxxyiqyqtvtgaumlrpctgxapbivrmuvgfnjtzekcqudmtkcavtosrtplrsinixmybdvydraopczpsoysrhcyjcatuseclbrnvmplftjwpnqodgogxnmdwhjupqswlxabwfvwetx\
  kvjumfsygosivvjoclvcupfpymycoslalncpuujahguyyniwhivmamausqlmvoykkiargypnjzsyemjwsisvliuqqshpgaioojhnkvkwhhyqveacivmyytepmoettthfkjvdyzxjcdzlvwddmtx\
  qkkforhfnylnwscqmzfxwfevsnafgvcusbyesfemxxuxjufpbdtyumituqfzuhkwvwzkaxpuvmcrraexmsxsgevfnyfyacsddryrvjdprcgqqpenaaotfiacncqwctwzacgrhcaipveetxsgbrr\
  fpgqjflxhovcybtixbwyujzbxnayekrrohvezmxllisqfwkdchyscgizvcxqaxlcbipmwbkfhiscecqhchomggsinkhaxejivpuvbvryughuwqkssozrcxwovwvgiemkrmxzrjbbnkhfpegcmgy\
  eacuxphnwgxuillfkbpvglxizyquaohacbbqdbvanzeikwpkaolbfcxrgowtlpjzubtbygxpuywtilpplplxatnnbbszrhvhfnimcvohdroihpjhdqugedxonsnouzixkzhvvxqaiqhxhjmiveumxrzmbnwvcqoqdcvqbjahclusfykjokpjgggvznzqcpmvbqvmsswjymlabqnvxsocihyqkvxkotwbofokqwaulgevgpymojyruqxmjvgpspypwcivxdchbbfxtazjgilqegpxvgtlucolqgwjfqueijqtlfrbrgmmuskfukjccxkagtzhxocpdktjryfbzqsgnpogronluzpopkpjaodumevbcjxnaejrllebsurbaqrfstgascjrkfcgaryhbfydjarudgerscptgupntkoeriilbcsevulqahixwnnjxlclgigbvilhafrsowhgogqaripoznmiyxcaddtqvjiuongbbtaanhnyrcctbvggubeoysdwcsvtgzqxyjcjeoepapfcldouxkauifuttzdteoryonqyofyqozgeurcwopqwqhhonppljatblcizsxmlwzcckcyiovzrwdqjruvxtcytybouskstzzfaimamcdaoynvcxenbnqdgkiuwltynfylyebkgbzscjfxcfnintwpmfynllhoodppjvqxfyqtlxfwkuqqmtztjbyjirqgfirfvoogaugmozuqqlsywguodxbsljqsuzsmxnozwiljwnbirwwwnsiamwynalgzqfkofxlixynomtjfawtboscbdkzrnbexniskaagjzkujvjagpnhmjtmemblpvcbemjcwnjhgrbsaxnwfgnavlfhcjryrslqtjkktlywdhufcavhssvpltsgkoulcvmsieovldkdlhamzlaqhfcamdwzvzxwkfwlntzkxbjbsfkeukkfuwznfbmcxrnqgbgmhvsoqdgxaaqecvfrxkqyqrjmojqbqzxkxxashfvaxzjamnzqtejfsbwetgdtrhucrwiopbloifhatlnqqqubxdalotpoiaywammuvdeokvumfqxyytaimiynkoelugpuwjrdtfwvupjwxxjbkbxmpiyzlfiikebfocmoftxpyhveobtxqleyuqhratmlljtaaqorwbbmrryvgwbdqnezibfgqvnmtlgcabqzhrjngjxgmnvwtozgrtpdvrmjtlrmcwzpnzcqmumwzpoadprsirmbssahqpagmqtiisgbrbqxpbbiwvwqbvhcbtqkihwhimogugsowlxgkcjpjzajevfmtcbmdigmhokcdtmuluzxvoliyfxrzvqutybfpboxxgvhnlkcmupkveswnmazsnmebfbdpomhmxpnrkivmqubdmdfsaihapeuoxonplcjtrlnzlviyjxsngsfvwdugmwkdchppwkmbwanpcppftogcqujgeczxevauijazabtirkjidodwgkxsfjepbhzwlmajssoosmzutsbwbfxdbxdzvadwikdgowhwnzlbwcfweebolhoqwxkwfqlamxqtvkyvoyjqhjvwjnsxjwdmghobsqmjrjjpasksfwbqrhajsvmvpenfenwreieuoiuhkoopqsgfexxshezmdxddyhoigwdcvaxeurlbzszfvdqxnohpvdmlowfbqodmyddmtilsvxmoxhrtqwpsgjadvxyfhphlhmbkcxzezmfgwowavsdnmmixvdcbdzenpeioxcmxtrjfywmcuiqlqlsqsaybpugultvagzrwgzxyuwnmqoflbuwderbkwvfdhywcoyhybuzddjbifwnwpvdzgxkibflmnpdabbcldsfezgdjmzbhcckexhatthxnfkbirqsrjjniazvjksdfsvhiafloydhvftmztkbeitxvepqwzsqwqirdweuwwzzutohtltjdmkyqjvtiydtjacinvhgrbfbtqbeynzgokxnpsmwshfobtufcymwxxzwdzyptpssalitdfrpsooaqhqknravmlxnztqqbzuwvbsmyqxdlilzifgnqvsqsneksibccyiufylrjtazuniarigugxfljtbxhvhbgtjppleibhiktcwzqkztjllnyfeeqoegydygacwaiavyclyncswmkjpadqwfwdgtpmvnfbmaugntyuwbcqucykkutkavxewswcgfvtctbtwalmiindsuqdgsqlaxrucdbcbitoocjdobglgcgznhfqigsnlxujvmkwamozilkitggogeptavmqblybapgcmpxlsicphtwmwpuawmmvcyuecejlfsqhxarynspwbixdjeadefmaomrvvfvrssbugbxmwjsjsyqmiitspphbsvxbelwdtfabjqnuxzjzphshexhttaixnkbajinnbjaqrztzwmiegsscxlefgtvtmnejjgihxvuzvnljbbvqyitoymirjesqjtaomdmhhswtukephqkjdvddrmclbzgnkqkyquidrxkltgjluaxkecomuepvgqhjddjysjjufdwevnxusypvrofqbvsjrccpntezjqtngtjkgyfqvaulwzfufypccoxjkgghnmzzdntwihktjdgiohkaxkynfsuibyjaniviyvgfggpeqlnqihxhrksjmshjlwvvesokunsivgxjpxlcbbenadztbnvdowsoemisgxckpdmzhbjqpydchhkdzftgpvoshdvcegnybjzhjujnoxjqyfxpipprvfsnabhalcqnivyndohxoudeikxaxkonmsoqhkjxikmpqzjysrnzzgktpynocucnaxydmmqlkcbrckrmuazmtvkubvuvmujlxougppqghvdabmyoyfymekzxdlcnbetkemcclunoegpafdcxrhhmyzncbgenocfsqpstsnnlwkkpahsyrzbvfyymjcbnowsllodbmhcfelywxvrmdwynxayyrusuvubeofswxlwhhnjsmgwgeylvbyymfejpuwqlsioiwhhviqciyvwnoqkrritwjomvydesujcdpdfnkoepodqdnbxivocijlevlbngteytfuksdyhzqdwzfmzskuizbxdtwwuipdjacnxlbxgsysquboswmqtvlumykuiykmpvxbshxwfzpjngnauivajipqherfbxeswlngsmojbdhizfwatyikgwrpuqmyvjsguynfuzzpbdsaolrbgclxphxyhpphufjbpoxmjvixayjuhqioahqiejcqohyjfqwwopvpkoucitwrksbqvufiqmbgkmnfskuzimtdenwqkiceclmrsqvanwhsjhhazaxvhrvggdcjuauukkbedwztvhyhnlbhgmggnxnshjmdhxidhnrbijfrpimqpavjdchmuswtjlqdtblqbqlstkvpkbwejlmoyfefxdhqouvwhrlwzpmgatamarlfjlapgcefpxpektnrqptvniwakigkaz";

d1 = new Date();
console.log(firstNonRepeatingChar("aaabcccdeeef"));
d2 = new Date();

console.log(`Time execution is : ${d2 - d1}`);

d1 = new Date();
console.log(firstNonRepeatingChar(dat));
d2 = new Date();

console.log(`Time execution is : ${d2 - d1}`);

function firstNonRepeatingChar(data) {
  const firstChar = data.split("").reduce((allChar, char) => {
    if (char in allChar) {
      allChar[char]++;
    } else {
      allChar[char] = 1;
    }
    return allChar;
  }, []);

  for (let index = 0; index < Object.values(firstChar).length; index++) {
    if (Object.values(firstChar)[index] === 1) {
      return `The first non repeating character is: ${Object.keys(firstChar)[index]}`;
    }
  }
}
